### ISSUE TITLE
[Keymanweb.com] Clicking the Twitter icon shows an error message on the page

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keymanweb.com#95] opened 2023-12-07 13:47 UTC
Here, What I did is:
1. Opened KeymaWeb.com on Chrome browser. (in an Android Mobile (ver 13) )
2. Selected a keyboard (eg., USBasic-Tagalog) using the globe key. 
3. Type some texts in the text area. 
4. Clicked the Twitter icon.

I noticed that after clicking the Twitter icon, an error message appeared on the Screen. I was not able to use Twitter. Seems to be an issue. 

Note: 
1. Able to reproduce this issue in iPhone 13 mobile device. 
2. Able to reproduce this in KeymanWeb 16.0.144 Stable and Alpha builds

..in Android Mobile 

   <img width="300" src="https://github.com/keymanapp/keymanweb.com/assets/19683143/be63c961-13b5-4595-923d-476b2f0a5d35">

..iPhone 13 Mobile

   <img width="300" src="https://github.com/keymanapp/keymanweb.com/assets/19683143/e55ed10c-d8af-4a97-b4cf-bfe149978d03">

**Comment by jahorton** [comment] 2024-04-09 03:17
Duplicate of #4 - it even has the same error message in the screenshot.

**Closed by jahorton** 2024-04-09 03:17 UTC
Labels: bug
